[project]
name = "reproca"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "aspizu", email = "aspizu@protonmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "msgspec>=0.19.0",
    "starlette>=0.47.1",
    "typing-extensions>=4.14.1",
]

[dependency-groups]
dev = [
    "uvicorn>=0.35.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pyright]
reportUnnecessaryTypeIgnoreComment = true
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportMissingModuleSource = false
reportMissingTypeStubs = false
reportWildcardImportFromLibrary = false
reportPrivateUsage = false
reportPrivateImportUsage = false
reportAny = false
reportExplicitAny = false
reportUnusedCallResult = false
reportImportCycles = false
reportImplicitStringConcatenation = false

[tool.ruff.lint]
select = ["ALL"]
extend-safe-fixes = ["ALL"]
unfixable = ["F841"]
ignore = ["COM", "D", "FBT", "ANN401", "S101", "N802", "F841", "PLR0913"]

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
